[package]
name = "concurrency-with-rust"
version = "0.1.0"
edition = "2021"

[dependencies]

[workspace]
members = [ "deadlocks", "divide_work", "mutexes", "not-a-footgun", "poisoner", "rwlocks", "scoped_threads", "thread_builder", "dashmap_wordcounter"]
