[package]
name = "concurrency-with-rust"
version = "0.1.0"
edition = "2021"

[dependencies]

[workspace]
members = [
    "divide_work", "mutexes", "not-a-footgun", 
    "scoped_threads", 
    "thread_builder"
]
